// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"week04/internal/biz"
	"week04/internal/data"
)

// Injectors from wire.go:

func InitArticleUseCase() *biz.ArticleUseCase {
	articleRepo := data.NewArticleRepo()
	articleUseCase := biz.NewArticleUseCase(articleRepo)
	return articleUseCase
}
